//
// Generated file, do not edit! Created by opp_msgtool 6.2 from src/messages/Packet.msg.
//

#ifndef __PACKET_M_H
#define __PACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0602
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class Packet;
/**
 * Class generated from <tt>src/messages/Packet.msg:6</tt> by opp_msgtool.
 * <pre>
 * message Packet
 * {
 *     int priorityLevel;     // 3=high, 2=medium, 1=low
 *     string type;           // "voice", "video", "data"
 *     simtime_t timestamp;   // creation time
 * }
 * </pre>
 */
class Packet : public ::omnetpp::cMessage
{
  protected:
    int priorityLevel = 0;
    omnetpp::opp_string type;
    omnetpp::simtime_t timestamp = SIMTIME_ZERO;

  private:
    void copy(const Packet& other);

  protected:
    bool operator==(const Packet&) = delete;

  public:
    Packet(const char *name=nullptr, short kind=0);
    Packet(const Packet& other);
    virtual ~Packet();
    Packet& operator=(const Packet& other);
    virtual Packet *dup() const override {return new Packet(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getPriorityLevel() const;
    virtual void setPriorityLevel(int priorityLevel);

    virtual const char * getType() const;
    virtual void setType(const char * type);

    virtual omnetpp::simtime_t getTimestamp() const;
    virtual void setTimestamp(omnetpp::simtime_t timestamp);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Packet& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Packet& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline Packet *fromAnyPtr(any_ptr ptr) { return check_and_cast<Packet*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __PACKET_M_H

